[package]
name = "render_tests"
version = "0.3.1"
authors = ["Gal Schlezinger <gal@spitfire.co.il>"]
edition = "2021"
publish = false
repository = "https://github.com/Schniz/render.rs"

[dependencies]
render = { path = "../render" }

[dev-dependencies]
pretty_assertions = "0.6"
trybuild = "1.0"
